matrix:
  include:
  - language: bash
    script:
    - bash linux_mac/magpi-education-downloader.sh
    - bash linux_mac/magpi-issue-downloader.sh
    - bash linux_mac/magpi-issue-downloader.sh -f 72 -l 74
    - bash linux_mac/magpi-issue-downloader_french.sh
    - bash linux_mac/magpi-issue-downloader_hebrew.sh
    - bash linux_mac/magpi-issue-downloader_italian.sh
    - bash linux_mac/magpi-issue-downloader_spanish.sh
    - bash linux_mac/magpi-special-issue-downloader.sh
  - language: bash
    services:
      - docker
      # Replace with your image name.
    script:
      - docker pull microsoft/powershell
      - docker run -v $(pwd):/data microsoft/powershell /bin/sh -c "cd /data; chmod +x ./windows/*.ps1; pwsh ./windows/magpi-education-downloader.ps1"
      - docker run -v $(pwd):/data microsoft/powershell /bin/sh -c "cd /data; chmod +x ./windows/*.ps1; pwsh ./windows/magpi-issue-downloader.ps1 -l 3"
      - docker run -v $(pwd):/data microsoft/powershell /bin/sh -c "cd /data; chmod +x ./windows/*.ps1; pwsh ./windows/magpi-issue-downloader.ps1 -f 92 -l 93"
      - docker run -v $(pwd):/data microsoft/powershell /bin/sh -c "cd /data; chmod +x ./windows/*.ps1; pwsh ./windows/magpi-issue-downloader_french.ps1"
      - docker run -v $(pwd):/data microsoft/powershell /bin/sh -c "cd /data; chmod +x ./windows/*.ps1; pwsh ./windows/magpi-issue-downloader_hebrew.ps1"
      - docker run -v $(pwd):/data microsoft/powershell /bin/sh -c "cd /data; chmod +x ./windows/*.ps1; pwsh ./windows/magpi-issue-downloader_italian.ps1"
      - docker run -v $(pwd):/data microsoft/powershell /bin/sh -c "cd /data; chmod +x ./windows/*.ps1; pwsh ./windows/magpi-issue-downloader_spanish.ps1"
      - docker run -v $(pwd):/data microsoft/powershell /bin/sh -c "cd /data; chmod +x ./windows/*.ps1; pwsh ./windows/magpi-special-issue-downloader.ps1"

