## This is a basic workflow to help you get started with Actions
#
#name: Language Issues Test Scripts
#
## Controls when the action will run. Triggers the workflow on push or pull request
## events but only for the main branch
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#
## A workflow run is made up of one or more jobs that can run sequentially or in parallel
#jobs:
#  powershell:
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v3.1.0
#      - name: Download French Issues
#        id: frenchIssues
#        shell: pwsh
#        run: ./windows/magpi-issue-downloader_french.ps1
#      - name: Download Hebrew Issues
#        id: hebrewIssues
#        shell: pwsh
#        run: ./windows/magpi-issue-downloader_hebrew.ps1
#      - name: Download Italian Issues
#        id: italianIssues
#        shell: pwsh
#        run: ./windows/magpi-issue-downloader_italian.ps1
#      - name: Download Spanish Issues
#        id: spanishIssues
#        shell: pwsh
#        run: ./windows/magpi-issue-downloader_spanish.ps1
#      - name: "Check file existence Windows"
#        id: check_files
#        uses: andstor/file-existence-action@v1.1.0
#        with:
#          files: "french_issues/MagPi_Mini_French_01.pdf, italian_issues/MagPi_Mini_Italian_02.pdf, hebrew_issues/MagPi_Mini_Hebrew_01.pdf, spanish_issues/MagPi_Mini_Spanish_03.pdf"
#          allow_failure: false
#      - name: lslah issues
#        run: Get-ChildItem â€“path D:\a\MagPiDownloader\MagPiDownloader\french_issues,D:\a\MagPiDownloader\MagPiDownloader\italian_issues,D:\a\MagPiDownloader\MagPiDownloader\hebrew_issues,D:\a\MagPiDownloader\MagPiDownloader\spanish_issues
#      - name: File exists
#        if: steps.check_files.outputs.files_exists == 'false'
#        run: exit 1
#
#  bash-linux:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3.1.0
#      - name: Download French Issues
#        id: frenchIssues
#        run: bash ./linux_mac/magpi-issue-downloader_french.sh
#      - name: Download Hebrew Issues
#        id: hebrewIssues
#        run: bash ./linux_mac/magpi-issue-downloader_hebrew.sh
#      - name: Download Italian Issues
#        id: italianIssues
#        run: bash ./linux_mac/magpi-issue-downloader_italian.sh
#      - name: Download Spanish Issues
#        id: spanishIssues
#        run: bash ./linux_mac/magpi-issue-downloader_spanish.sh
#      - name: "Check file existence Linux"
#        id: check_files
#        uses: andstor/file-existence-action@v1.1.0
#        with:
#          files: "french_issues/MagPi_Mini_French_01.pdf, italian_issues/MagPi_Mini_Italian_02.pdf, hebrew_issues/MagPi_Mini_Hebrew_01.pdf, spanish_issues/MagPi_Mini_Spanish_03.pdf"
#          allow_failure: false
#      - name: lslah
#        run: ls -lah french_issues/ italian_issues/ hebrew_issues/ spanish_issues/
#      - name: File exists
#        if: steps.check_files.outputs.files_exists == 'false'
#        run: exit 1
#  bash-macos:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v3.1.0
#      - name: Download French Issues
#        id: frenchIssues
#        run: bash ./linux_mac/magpi-issue-downloader_french.sh
#      - name: Download Hebrew Issues
#        id: hebrewIssues
#        run: bash ./linux_mac/magpi-issue-downloader_hebrew.sh
#      - name: Download Italian Issues
#        id: italianIssues
#        run: bash ./linux_mac/magpi-issue-downloader_italian.sh
#      - name: Download Spanish Issues
#        id: spanishIssues
#        run: bash ./linux_mac/magpi-issue-downloader_spanish.sh
#      - name: "Check file existence MacOs"
#        id: check_files
#        uses: andstor/file-existence-action@v1.1.0
#        with:
#          files: "french_issues/MagPi_Mini_French_01.pdf, italian_issues/MagPi_Mini_Italian_02.pdf, hebrew_issues/MagPi_Mini_Hebrew_01.pdf, spanish_issues/MagPi_Mini_Spanish_03.pdf"
#          allow_failure: false
#      - name: lslah
#        run: ls -lah french_issues/ italian_issues/ hebrew_issues/ spanish_issues/
#      - name: File exists
#        if: steps.check_files.outputs.files_exists == 'false'
#        run: exit 1
